apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodejs-api-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-api
  template:
    metadata:
      labels:
        app: nodejs-api
    spec:
      containers:
      - name: nodejs-api
        image: shrutinagp2024/node-image:4
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: mysql-host
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: mysql-password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: mysql-database
